export type GroupString =
    | "length"
    | "mass"
    | "pressure"
    | "time"
    | "area"
    | "temperature"
    | "digital"
    | "speed"
    | "energy"
    | "volume"
    | "current"
    | "voltage"
    | "power"
    | "parts-per"
    | "force";
